---
name: Apollo
description: Apollo schema checks with rover
author: Datum
requirements:
  - bash
  - curl
configuration:
  properties:
    graph-ref: # The name of the apollo graph to check
      type: string
    subgraph: # The name of the subgraph to check
      type: string
    schema:  # The schema to check, defaults to schema.graphql 
      type: string
    ignore-existing: # Ignore existing lint errors and only return new errors
      type: boolean
      default: false
  required:
    - graph-ref
    - subgraph
    - schema
  additionalProperties: false